import React, { useEffect } from "react";
import Head from "next/head";
import Main from "../components/Main";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Web Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <main>
        <div className="">
          {/* searsh bar and rooms */}
          <div>
            <Main />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
